<?php

use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\Entity\EntityViewDisplay;

/**
 * Implementa hook_install().
 * Se ejecuta cuando el módulo es instalado.
 */
function cliente_install() {
    // Verifica si el almacenamiento del campo ya existe.
    if (!FieldStorageConfig::loadByName('user', 'field_dni')) {
        // Crear el almacenamiento del campo.
        $field_storage = FieldStorageConfig::create([
            'field_name' => 'field_dni',
            'entity_type' => 'user',
            'type' => 'string',
            'settings' => [
                'max_length' => 20,
                'is_ascii' => FALSE,
                'case_sensitive' => FALSE,
            ],
            'module' => 'text',
            'locked' => FALSE,
            'cardinality' => 1,
            'translatable' => FALSE,
        ]);
        $field_storage->save();

        // Crear la configuración del campo para el usuario.
        $field = FieldConfig::create([
            'field_storage' => $field_storage,
            'bundle' => 'user',
            'label' => 'DNI',
            'description' => 'Número de identificación',
            'required' => FALSE,
            'translatable' => FALSE,
            'default_value' => [],  // <-- Cambiado de NULL a []
            'settings' => [],
        ]);
        $field->save();
        

        // Agregar el campo a la visualización del formulario de usuario.
        $form_display_id = 'user.user.default';
        $form_display = EntityFormDisplay::load($form_display_id);
        if (!$form_display) {
            $form_display = EntityFormDisplay::create([
                'targetEntityType' => 'user',
                'bundle' => 'user',
                'mode' => 'default',
                'status' => TRUE,
                'id' => $form_display_id,
            ]);
        }
        $form_display->setComponent('field_dni', [
            'type' => 'string_textfield',
            'weight' => 5,
        ])->save();

        // Agregar el campo a la visualización de la entidad usuario.
        $view_display_id = 'user.user.default';
        $view_display = EntityViewDisplay::load($view_display_id);
        if (!$view_display) {
            $view_display = EntityViewDisplay::create([
                'targetEntityType' => 'user',
                'bundle' => 'user',
                'mode' => 'default',
                'status' => TRUE,
                'id' => $view_display_id,
            ]);
        }
        $view_display->setComponent('field_dni', [
            'label' => 'above',
            'type' => 'string',
            'weight' => 5,
        ])->save();
    }
}