producto.add_form:
  path: '/admin/producto/add'
  defaults:
    _entity_form: 'producto.add'
    _title: 'Añadir Producto'
  requirements:
    _permission: 'producto.add'

producto.edit_form:
  path: '/admin/producto/{producto}/edit'
  defaults:
    _entity_form: 'producto.edit'
    _title: 'Editar Producto'
  requirements:
    _permission: 'producto.update'

producto.delete_form:
  path: '/admin/producto/{producto}/delete'
  defaults:
    _entity_form: 'producto.delete'
    _title: 'Eliminar Producto'
  requirements:
    _permission: 'producto.delete'

entity.producto.canonical:
  path: '/admin/producto/{producto}'
  defaults:
    _entity_view: 'producto.full'
    _title: 'Visualizar Producto'
  requirements:
    _permission: 'producto.view'

entity.producto.collection:
  path: '/admin/producto'
  defaults:
    _entity_list: 'producto'
    _title: 'Lista de Productos'
  requirements:
    _permission: 'producto.view'
