name: 'Producto'
type: module
description: 'Funcionalidades complementarias para la gestión de productos.'
core_version_requirement: ^11
package: Custom
dependencies:
  - drupal:field
  - drupal:text
  - drupal:user